wget https://raw.githubusercontent.com/muschellij2/neuroc/master/getting_ready_for_submission/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/getting_ready_for_submission.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/continuous_integration/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/continuous_integration.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/faq/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/faq.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/windows_wsl/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/windows_wsl.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/installing_devtools/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/installing_devtools.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/installing_ANTsR/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/installing_ANTsR.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/nifti_basics/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/nifti_basics.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/neurohcp/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/neurohcp.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/fcp_indi/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/fcp_indi.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/brain_extraction/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/brain_extraction.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/ss_ct/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/ss_ct.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/tissue_class_segmentation/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/tissue_class_segmentation.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/label_image/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/label_image.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/preprocess_mri_within/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/preprocess_mri_within.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/cortical_thickness/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/cortical_thickness.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/fmri_analysis_ANTsR/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/fmri_analysis_ANTsR.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/fmri_analysis_fslr/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/fmri_analysis_fslr.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/fmri_analysis_spm12r/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/fmri_analysis_spm12r.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/DTI_analysis_fslr/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/DTI_analysis_fslr.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/DTI_analysis_rcamino/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/DTI_analysis_rcamino.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/DTI_analysis_rcamino_hcp/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/DTI_analysis_rcamino_hcp.html
wget https://raw.githubusercontent.com/muschellij2/neuroc/master/ms_lesion/index_notoc.html -O /var/www/neuroc_development/html/sites/default/files/help/ms_lesion.html

wget https://raw.githubusercontent.com/muschellij2/neurocInstall/master/neurocLite.R -O /var/www/neuroc_development/html/sites/default/files/neurocLite.R
