---
title: "Neuroconductor"
date: '`r Sys.Date()`'
output: 
  html_document:
    keep_md: true
    theme: cosmo
    toc: true
    toc_depth: 1
    toc_float:
      collapsed: false
---

# Frequently Asked Questions (FAQ)

Please visit the [FAQ](faq/index.html) for information on how to begin.

# Installation Guides {#install}

1. [Installing devtools](installing_devtools/index.html)
2. [Installing ANTsR](installing_ANTsR/index.html)

# Required Readings {#req}

1. [NIfTI Basics](nifti_basics/index.html)

# Data
1. [Downloading Human Connectome Project Data](hcp/index.html)

# General Tutorials {#tutorials}

1. [Brain Extraction](brain_extraction/index.html)
2. [Tissue-Class Segmentation](tissue_class_segmentation/index.html)
3. [Labeling Brain Structures](label_image/index.html)
4. [Resting-State fMRI analysis using ANTsR](fmri_analysis_ANTsR/index.html)
5. [Resting-State fMRI analysis using fslr](fmri_analysis_ANTsR/index.html)
6. [Processing Within-Visit Structural MRI](preprocess_mri_within/index.html)
7. [DTI analysis with fslr](DTI_analysis_fslr/index.html)
8. [DTI analysis with Camino](DTI_analysis_rcamino/index.html)
9. [Cortical Thickness Estimation (NOT DONE)](cortical_thickness/index.html)

# Disease-specific Tutorials

1. [Multiple Sclerosis Lesion Segmentation](ms_lesion/index.html)

