wget -O getting_ready_for_submission.html https://raw.githubusercontent.com/muschellij2/neuroc/master/getting_ready_for_submission/index_notoc.html
wget -O continuous_integration.html https://raw.githubusercontent.com/muschellij2/neuroc/master/continuous_integration/index_notoc.html
wget -O faq.html https://raw.githubusercontent.com/muschellij2/neuroc/master/faq/index_notoc.html
wget -O windows_wsl.html https://raw.githubusercontent.com/muschellij2/neuroc/master/windows_wsl/index_notoc.html
wget -O installing_devtools.html https://raw.githubusercontent.com/muschellij2/neuroc/master/installing_devtools/index_notoc.html
wget -O installing_ANTsR.html https://raw.githubusercontent.com/muschellij2/neuroc/master/installing_ANTsR/index_notoc.html
wget -O nifti_basics.html https://raw.githubusercontent.com/muschellij2/neuroc/master/nifti_basics/index_notoc.html
wget -O neurohcp.html https://raw.githubusercontent.com/muschellij2/neuroc/master/neurohcp/index_notoc.html
wget -O fcp_indi.html https://raw.githubusercontent.com/muschellij2/neuroc/master/fcp_indi/index_notoc.html
wget -O brain_extraction.html https://raw.githubusercontent.com/muschellij2/neuroc/master/brain_extraction/index_notoc.html
wget -O tissue_class_segmentation.html https://raw.githubusercontent.com/muschellij2/neuroc/master/tissue_class_segmentation/index_notoc.html
wget -O label_image.html https://raw.githubusercontent.com/muschellij2/neuroc/master/label_image/index_notoc.html
wget -O preprocess_mri_within.html https://raw.githubusercontent.com/muschellij2/neuroc/master/preprocess_mri_within/index_notoc.html
wget -O cortical_thickness.html https://raw.githubusercontent.com/muschellij2/neuroc/master/cortical_thickness/index_notoc.html
wget -O fmri_analysis_ANTsR.html https://raw.githubusercontent.com/muschellij2/neuroc/master/fmri_analysis_ANTsR/index_notoc.html
wget -O fmri_analysis_fslr.html https://raw.githubusercontent.com/muschellij2/neuroc/master/fmri_analysis_fslr/index_notoc.html
wget -O fmri_analysis_spm12r.html https://raw.githubusercontent.com/muschellij2/neuroc/master/fmri_analysis_spm12r/index_notoc.html
wget -O DTI_analysis_fslr.html https://raw.githubusercontent.com/muschellij2/neuroc/master/DTI_analysis_fslr/index_notoc.html
wget -O DTI_analysis_rcamino.html https://raw.githubusercontent.com/muschellij2/neuroc/master/DTI_analysis_rcamino/index_notoc.html
wget -O DTI_analysis_rcamino_hcp.html https://raw.githubusercontent.com/muschellij2/neuroc/master/DTI_analysis_rcamino_hcp/index_notoc.html
wget -O ms_lesion.html https://raw.githubusercontent.com/muschellij2/neuroc/master/ms_lesion/index_notoc.html
