---
author: John Muschelli
output:
  html_document:
    theme: cosmo
---
# Installing devtools
John Muschelli  
October 3, 2016  



As Neuroconductor is GitHub-based, we will need a way for R to install packages directly from GitHub.  The `devtools` package provides this functionality.  In this tutorial, we will go through the steps of installing `devtools`, and some common problems.  You must have `devtools` installed to install from GitHub in subsequent tutorials on installing Neuroconductor packages.

There are other packages that will do this and are more lightweight (see `remotes` and `ghit`), but we will focus on `devtools`. 


# Mac OSX

You need to install [Command Line Tools](https://developer.apple.com/library/content/technotes/tn2339/_index.html), aka the command line tools for Xcode, if you have not already.  [http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/](http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/) is a great tutorial how.

# Installing devtools

If you already have `devtools` installed great! (Why are you here?)  You can always reinstall the most up to date version from the steps below.


```r
packages = installed.packages()
packages = packages[, "Package"]
if (!"devtools" %in% packages) {
  install.packages("devtools")
}
```

# The `remotes` and `ghit` packages
If you want a lighter-weight package that has the `install_github` functionality that `devtools` provides, but not all the "development" parts of `devtools`, the `remotes` package exists just for that:


```r
packages = installed.packages()
packages = packages[, "Package"]
if (!"remotes" %in% packages) {
  install.packages("remotes")
}
```

The `ghit` package is the lightest-weight package I have seen which has a `install_github` funciton, but may have some limited functionality compared to `remotes` in the functionality of installing package with dependencies in other systems, such as BitBucket.

In any subsequent tutorial, when you see `devtools::install_github`, just insert `remotes::install_github` and it should work just the same.


# Updating a package

In the `install_github` function, there are additional options to pass to the `install` function from `devtools`.  One of those arguments is `upgrade_dependencies`, which default is set to `TRUE`.  So if you want to install a package from GitHub, but not update any of the dependencies, then you can use `install_github(..., upgrade_dependencies = FALSE)`.  

# Troubleshooting errors 

## git2r dependency in devtools

If you cannot install `devtools`, many times it is due to `git2r`.  You should look at the installation logs and if you see something like:

```
   The OpenSSL library that is required to
   build git2r was not found.

   Please install:
libssl-dev    (package on e.g. Debian and Ubuntu)
openssl-devel (package on e.g. Fedora, CentOS and RHEL)
openssl       (Homebrew package on OS X)
```

Then run `sudo apt-get libssl-dev` or `sudo yum install openssl-devel` on your respective Linux machine.  Try to re-install `devtools`.

### Mac OSX

For Mac, you have to [install Homebrew](http://www.howtogeek.com/211541/homebrew-for-os-x-easily-installs-desktop-apps-and-terminal-utilities/) which the tutorial is located in the link.  After Homebrew is installed you should be able to type in the Terminal:
```
brew update
brew install openssl
```
Then try to re-install `devtools`.

# Session Info


```r
devtools::session_info()
```

```
## Session info --------------------------------------------------------------
```

```
##  setting  value                       
##  version  R version 3.3.1 (2016-06-21)
##  system   x86_64, darwin13.4.0        
##  ui       X11                         
##  language (EN)                        
##  collate  en_US.UTF-8                 
##  tz       America/New_York            
##  date     2016-11-09
```

```
## Packages ------------------------------------------------------------------
```

```
##  package    * version date       source                            
##  assertthat   0.1     2013-12-06 CRAN (R 3.2.0)                    
##  colorout   * 1.1-0   2015-04-20 Github (jalvesaq/colorout@1539f1f)
##  devtools     1.12.0  2016-06-24 CRAN (R 3.3.0)                    
##  digest       0.6.10  2016-08-02 cran (@0.6.10)                    
##  evaluate     0.9     2016-04-29 CRAN (R 3.2.5)                    
##  formatR      1.4     2016-05-09 CRAN (R 3.2.5)                    
##  htmltools    0.3.6   2016-09-26 Github (rstudio/htmltools@6996430)
##  knitr        1.14    2016-08-13 CRAN (R 3.3.0)                    
##  magrittr     1.5     2014-11-22 CRAN (R 3.2.0)                    
##  memoise      1.0.0   2016-01-29 CRAN (R 3.2.3)                    
##  Rcpp         0.12.7  2016-09-05 cran (@0.12.7)                    
##  rmarkdown    1.1     2016-10-16 CRAN (R 3.3.1)                    
##  stringi      1.1.1   2016-05-27 CRAN (R 3.3.0)                    
##  stringr      1.1.0   2016-08-19 cran (@1.1.0)                     
##  tibble       1.2     2016-08-26 CRAN (R 3.3.0)                    
##  withr        1.0.2   2016-06-20 CRAN (R 3.3.0)                    
##  yaml         2.1.13  2014-06-12 CRAN (R 3.2.0)
```

